version: "3.8"
services:
  client3:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client3
    ports:
      - "5003:5000"
    volumes:
      - config_client3:/app/client/config
      - chat_data_client3:/app/client/chat_data
    environment:
      - SERVER_ADDRESS=server2
      - SERVER_PORT=8767
      - HTTP_PORT=8082
      - LOG_MESSAGES=True
      - CLIENT_NAME=Client3
      - MESSAGE_EXPIRY_TIME=-1
    networks:
      - olaf_network

volumes:
  config_client3:
  chat_data_client3:

networks:
  olaf_network:
    driver: bridge
