version: "3.8"
services:
  server1:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: olaf_server1
    hostname: server1
    ports:
      - "8765:8765"
      - "8766:8766"
      - "8081:8081"
    volumes:
      - test_clients1:/app/server/clients
      - test_files1:/app/server/files
      - test_config1:/app/server/config
      - test_neighbours1:/app/server/neighbours
      - test_neighbours_shared:/app/server/test_neighbours
    environment:
      - BIND_ADDRESS=0.0.0.0
      - CLIENT_WS_PORT=8765
      - SERVER_WS_PORT=8766
      - HTTP_PORT=8081
      - NEIGHBOUR_ADDRESSES=server2:8766,server3:8766
      - LOG_MESSAGES=True
      - EXTERNAL_ADDRESS=server1
      - TEST_MODE=True
    networks:
      olaf_network:
        aliases:
          - server1

  server2:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: olaf_server2
    hostname: server2
    ports:
      - "8767:8765"
      - "8768:8766"
      - "8082:8081"
    volumes:
      - test_clients2:/app/server/clients
      - test_files2:/app/server/files
      - test_config2:/app/server/config
      - test_neighbours2:/app/server/neighbours
      - test_neighbours_shared:/app/server/test_neighbours
    environment:
      - BIND_ADDRESS=0.0.0.0
      - CLIENT_WS_PORT=8765
      - SERVER_WS_PORT=8766
      - HTTP_PORT=8081
      - NEIGHBOUR_ADDRESSES=server1:8766,server3:8766
      - LOG_MESSAGES=True
      - EXTERNAL_ADDRESS=server2
      - TEST_MODE=True
    networks:
      olaf_network:
        aliases:
          - server2

  server3:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: olaf_server3
    hostname: server3
    ports:
      - "8769:8765"
      - "8770:8766"
      - "8083:8081"
    volumes:
      - test_clients3:/app/server/clients
      - test_files3:/app/server/files
      - test_config3:/app/server/config
      - test_neighbours3:/app/server/neighbours
      - test_neighbours_shared:/app/server/test_neighbours
    environment:
      - BIND_ADDRESS=0.0.0.0
      - CLIENT_WS_PORT=8765
      - SERVER_WS_PORT=8766
      - HTTP_PORT=8081
      - NEIGHBOUR_ADDRESSES=server1:8766,server2:8766
      - LOG_MESSAGES=True
      - EXTERNAL_ADDRESS=server3
      - TEST_MODE=True
    networks:
      olaf_network:
        aliases:
          - server3

  client1:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client1
    ports:
      - "5001:5000"
    volumes:
      - test_config_client1:/app/client/config
      - test_chat_data_client1:/app/client/chat_data
    environment:
      - SERVER_ADDRESS=server1
      - SERVER_PORT=8765
      - HTTP_PORT=8081
      - LOG_MESSAGES=True
      - CLIENT_NAME=Client1
      - MESSAGE_EXPIRY_TIME=-1
      - TEST_MODE=True
    depends_on:
      - server1
    networks:
      - olaf_network

  client2:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client2
    ports:
      - "5002:5000"
    volumes:
      - test_config_client2:/app/client/config
      - test_chat_data_client2:/app/client/chat_data
    environment:
      - SERVER_ADDRESS=server2
      - SERVER_PORT=8765
      - HTTP_PORT=8082
      - LOG_MESSAGES=True
      - CLIENT_NAME=Client2
      - MESSAGE_EXPIRY_TIME=-1
      - TEST_MODE=True
    depends_on:
      - server2
    networks:
      - olaf_network

  client3:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client3
    ports:
      - "5003:5000"
    volumes:
      - test_config_client3:/app/client/config
      - test_chat_data_client3:/app/client/chat_data
    environment:
      - SERVER_ADDRESS=server3
      - SERVER_PORT=8765
      - HTTP_PORT=8083
      - LOG_MESSAGES=True
      - CLIENT_NAME=Client3
      - MESSAGE_EXPIRY_TIME=-1
      - TEST_MODE=True
    depends_on:
      - server3
    networks:
      - olaf_network

volumes:
  test_clients1:
  test_files1:
  test_config1:
  test_neighbours1:
  test_clients2:
  test_files2:
  test_config2:
  test_neighbours2:
  test_clients3:
  test_files3:
  test_config3:
  test_neighbours3:
  test_config_client1:
  test_chat_data_client1:
  test_config_client2:
  test_chat_data_client2:
  test_config_client3:
  test_chat_data_client3:
  test_neighbours_shared:

networks:
  olaf_network:
    driver: bridge
