version: "3.8"
services:
  server1:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: olaf_server1
    ports:
      - "8765:8765" # WebSocket port for clients
      - "8766:8766" # WebSocket port for servers
      - "8081:8081" # HTTP port for file transfers
    volumes:
      - clients1:/app/server/clients
      - files1:/app/server/files
      - config1:/app/server/config
      - neighbours:/app/server/neighbours
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8765
      - SERVER_SERVER_PORT=8766
      - HTTP_PORT=8081
      - NEIGHBOUR_ADDRESSES=unknownweb.ddns.net:81
      - LOG_MESSAGES=True
      - PUBLIC_HOST=localhost
      - PUBLIC_ADDRESS=203.221.52.227 # Added this line
    networks:
      - olaf_network

  client1:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client1
    ports:
      - "5001:5000"
    volumes:
      - config_client1:/app/client/config
      - chat_data_client1:/app/client/chat_data
    environment:
      - SERVER_ADDRESS=server1
      - SERVER_PORT=8765
      - LOG_MESSAGES=True
      - CLIENT_NAME=Client1
      - MESSAGE_EXPIRY_TIME=-1
    networks:
      - olaf_network
    depends_on:
      - server1

volumes:
  # server
  clients1:
  files1:
  config1:
  # shared neighbourhood
  neighbours:
  # client
  config_client1:
  chat_data_client1:

networks:
  olaf_network:
    driver: bridge
