# docker-compose.yml

version: "3.8"

services:
  server1:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: olaf_server1
    ports:
      - "8765:8765" # WebSocket port for clients
      - "8766:8766" # WebSocket port for servers
      - "8081:8081" # HTTP port for file transfers
    volumes:
      - ./server/clients:/app/server/clients
      - ./server/files:/app/server/files
    environment:
      - SERVER_ADDRESS=server1
      - SERVER_PORT=8765
      - HTTP_PORT=8081
      - NEIGHBOUR_ADDRESSES=server2:8765
    networks:
      - olaf_network

  server2:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: olaf_server2
    ports:
      - "8767:8765" # WebSocket port for clients
      - "8768:8766" # WebSocket port for servers
      - "8082:8081" # HTTP port for file transfers
    volumes:
      - ./server/clients2:/app/server/clients
      - ./server/files2:/app/server/files
    environment:
      - SERVER_ADDRESS=server2
      - SERVER_PORT=8765
      - HTTP_PORT=8081
      - NEIGHBOUR_ADDRESSES=server1:8765
    networks:
      - olaf_network

  client1:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client1
    ports:
      - "5001:5000"
    environment:
      - SERVER_ADDRESS=server1
      - SERVER_PORT=8765
    networks:
      - olaf_network
    depends_on:
      - server1

  client2:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client2
    ports:
      - "5002:5000"
    environment:
      - SERVER_ADDRESS=server2
      - SERVER_PORT=8765
    networks:
      - olaf_network
    depends_on:
      - server2

networks:
  olaf_network:
    driver: bridge
