version: "3.8"
services:
  client2:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: olaf_client2
    ports:
      - "5002:5000"
    volumes:
      - config_client2:/app/client/config
      - chat_data_client2:/app/client/chat_data
    environment:
      - SERVER_ADDRESS=203.221.52.227
      - SERVER_PORT=8765
      - HTTP_PORT=8081
      - LOG_MESSAGES=True
      - CLIENT_NAME=sam_local
      - MESSAGE_EXPIRY_TIME=-1
    networks:
      - olaf_network

volumes:
  config_client2:
  chat_data_client2:

networks:
  olaf_network:
    driver: bridge
