version: "3.8"
services:
  server2:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: olaf_server2
    ports:
      - "8765:8765" # WebSocket port for clients
      - "8766:8766" # WebSocket port for servers
      - "8081:8081" # HTTP port for file transfers
    volumes:
      - clients2:/app/server/clients
      - files2:/app/server/files
      - config2:/app/server/config
      - neighbours2:/app/server/neighbours
    environment:
      - BIND_ADDRESS=0.0.0.0
      - CLIENT_WS_PORT=8765
      - SERVER_WS_PORT=8766
      - HTTP_PORT=8081
      - NEIGHBOUR_ADDRESSES=65.108.216.173:8766
      - LOG_MESSAGES=True
      - EXTERNAL_ADDRESS=203.221.52.227
    networks:
      - olaf_network

volumes:
  clients2:
  files2:
  config2:
  neighbours2:

networks:
  olaf_network:
    driver: bridge
